services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_API_VERSION: ${VITE_API_VERSION}

    image: hamiyar-frontend
    container_name: hamiyar-frontend

    restart: unless-stopped

    ports:
      - "${FRONTEND_BIND_IP}:${FRONTEND_PORT}:80"